name: Build PSFree

on:
  push:
    branches: [ patch-2 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: patch-2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y binutils-gold make git clang lld

      - name: Clone libPS4
        run: |
          git clone https://github.com/idc/ps4-payload-sdk.git $HOME/PS4SDK

      - name: Build libPS4
        run: |
          cd $HOME/PS4SDK/libPS4
          make CC=clang CFLAGS="-target x86_64-pc-none-elf -ffreestanding -nostdlib -nostdinc -Iinclude -O2 -std=c11 -masm=intel -march=btver2 -mtune=btver2 -m64 -mabi=sysv -mcmodel=large"

      - name: Build project
        run: |
          export PS4SDK=$HOME/PS4SDK
          make CC=clang

      - name: Upload BIN artifact
        uses: actions/upload-artifact@v4
        with:
          name: psfree-bin
          path: "*.bin"
          retention-days: 30
